"""
PREDICT — Rules & Work Order Templates API
CRUD for rules and templates used by the rule engine.
Mutations invalidate the engine's in-process rule cache.
"""
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.database import get_db
from app.db.models import Rule, RuleType, Sensor, WorkOrderTemplate
from app.rules.engine import (
    BEHAVIOR_EVENT_TYPES,
    SCHEDULED_SENSOR_TYPES,
    OPERATORS,
    invalidate_rules_cache,
)
from app.schemas.schemas import (
    RuleCreate,
    RuleOut,
    RuleUpdate,
    WorkOrderTemplateCreate,
    WorkOrderTemplateOut,
)

router = APIRouter(prefix="/rules", tags=["rules"])


def _validate_rule_payload(rule_type, sensor_type, operator, threshold_value,
                           dtc_code, interval_value) -> Optional[str]:
    """Return an error message when the rule can never evaluate, else None."""
    if rule_type in (RuleType.THRESHOLD, "threshold"):
        if not sensor_type:
            return "Threshold rules require sensor_type"
        if operator not in OPERATORS:
            return f"Operator must be one of {sorted(OPERATORS)}"
        if threshold_value is None:
            return "Threshold rules require threshold_value"
    elif rule_type in (RuleType.DTC, "dtc"):
        if not dtc_code:
            return "DTC rules require dtc_code"
    elif rule_type in (RuleType.SCHEDULED, "scheduled"):
        if sensor_type not in SCHEDULED_SENSOR_TYPES:
            return f"Scheduled rules require sensor_type in {SCHEDULED_SENSOR_TYPES}"
        if not interval_value or interval_value <= 0:
            return "Scheduled rules require a positive interval_value"
    elif rule_type in (RuleType.BEHAVIOR, "behavior"):
        if sensor_type not in BEHAVIOR_EVENT_TYPES:
            return f"Behavior rules require sensor_type (event) in {BEHAVIOR_EVENT_TYPES}"
        if threshold_value is None:
            return "Behavior rules require threshold_value (event count)"
        if operator and operator not in OPERATORS:
            return f"Operator must be one of {sorted(OPERATORS)}"
    elif rule_type in (RuleType.ANOMALY, "anomaly"):
        return "Anomaly rules are auto-generated by the baselines job"
    return None


async def _provisioned_sensor_types(db: AsyncSession) -> set:
    result = await db.execute(select(Sensor.sensor_type).distinct())
    return {row[0] for row in result.all()}


def _rule_out(rule: Rule, provisioned: set) -> RuleOut:
    dormant = bool(
        rule.is_active
        and rule.rule_type in (RuleType.THRESHOLD, RuleType.SCHEDULED)
        and rule.sensor_type
        and rule.sensor_type not in provisioned
    )
    out = RuleOut.model_validate(rule)
    out.dormant = dormant
    return out


# =============================================================================
# Work Order Templates
# =============================================================================
@router.get("/templates", response_model=List[WorkOrderTemplateOut])
async def list_templates(db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(WorkOrderTemplate).order_by(WorkOrderTemplate.id))
    return result.scalars().all()


@router.post("/templates", response_model=WorkOrderTemplateOut, status_code=201)
async def create_template(data: WorkOrderTemplateCreate, db: AsyncSession = Depends(get_db)):
    template = WorkOrderTemplate(**data.model_dump())
    db.add(template)
    await db.flush()
    return template


@router.get("/templates/{template_id}", response_model=WorkOrderTemplateOut)
async def get_template(template_id: int, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(WorkOrderTemplate).where(WorkOrderTemplate.id == template_id))
    template = result.scalar_one_or_none()
    if not template:
        raise HTTPException(status_code=404, detail="Template not found")
    return template


@router.delete("/templates/{template_id}", status_code=204)
async def delete_template(template_id: int, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(WorkOrderTemplate).where(WorkOrderTemplate.id == template_id))
    template = result.scalar_one_or_none()
    if not template:
        raise HTTPException(status_code=404, detail="Template not found")
    await db.delete(template)   # rules referencing it get template_id = NULL
    invalidate_rules_cache()


# =============================================================================
# Rules
# =============================================================================
@router.get("", response_model=List[RuleOut])
async def list_rules(
    rule_type: Optional[str] = None,
    is_active: Optional[bool] = None,
    db: AsyncSession = Depends(get_db),
):
    stmt = select(Rule).order_by(Rule.id)
    if rule_type:
        stmt = stmt.where(Rule.rule_type == rule_type)
    if is_active is not None:
        stmt = stmt.where(Rule.is_active == is_active)
    result = await db.execute(stmt)
    rules = result.scalars().all()
    provisioned = await _provisioned_sensor_types(db)
    return [_rule_out(r, provisioned) for r in rules]


@router.post("", response_model=RuleOut, status_code=201)
async def create_rule(data: RuleCreate, db: AsyncSession = Depends(get_db)):
    err = _validate_rule_payload(
        data.rule_type, data.sensor_type, data.operator,
        data.threshold_value, data.dtc_code, data.interval_value,
    )
    if err:
        raise HTTPException(status_code=422, detail=err)
    rule = Rule(**data.model_dump())
    db.add(rule)
    await db.flush()
    invalidate_rules_cache()
    return _rule_out(rule, await _provisioned_sensor_types(db))


@router.get("/{rule_id}", response_model=RuleOut)
async def get_rule(rule_id: int, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Rule).where(Rule.id == rule_id))
    rule = result.scalar_one_or_none()
    if not rule:
        raise HTTPException(status_code=404, detail="Rule not found")
    return _rule_out(rule, await _provisioned_sensor_types(db))


@router.patch("/{rule_id}", response_model=RuleOut)
async def update_rule(rule_id: int, data: RuleUpdate, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Rule).where(Rule.id == rule_id))
    rule = result.scalar_one_or_none()
    if not rule:
        raise HTTPException(status_code=404, detail="Rule not found")
    for k, v in data.model_dump(exclude_unset=True).items():
        setattr(rule, k, v)
    err = _validate_rule_payload(
        rule.rule_type, rule.sensor_type, rule.operator,
        rule.threshold_value, rule.dtc_code, rule.interval_value,
    )
    if err:
        raise HTTPException(status_code=422, detail=err)
    await db.flush()
    invalidate_rules_cache()
    return _rule_out(rule, await _provisioned_sensor_types(db))


@router.delete("/{rule_id}", status_code=204)
async def delete_rule(rule_id: int, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Rule).where(Rule.id == rule_id))
    rule = result.scalar_one_or_none()
    if not rule:
        raise HTTPException(status_code=404, detail="Rule not found")
    await db.delete(rule)
    invalidate_rules_cache()